### ISSUE TITLE
webhook formats

### ISSUE THREAD

**Issue by needhamgary** [fabianmakila/WebhookLogger#14]
really neat mod, doing great so far. I only request that we get the option to send it as an embed if the webhook is going to Discord. This would enhance the experience a lot IMO!

**Comment by fabianmakila** [comment]
What's the benefit of using embeds over normal messages?

All I can think of is slightly different background that the embeds have. But at the same time those embeds can be accidentally closed much more easily since those have the extra "X" button which deletes the embed.

While I'm not completely against this, I personally see very little benefits using this:
![image](https://github.com/user-attachments/assets/4225469d-48a9-4fa8-a70b-02410b3554aa)

Over just this:
![image](https://github.com/user-attachments/assets/b33195fb-8874-4474-8a55-8e738c3de995)

**Comment by needhamgary** [comment]
I mean you are correct. I think it's just a personal preference. Here is an example of what I would like. Not necessarily on every event, just to toggle it on user side.
```yaml
webhooks:
- url: ''
- embed: true or false
  events:
  - CHAT
```

**Comment by needhamgary** [comment]
Whether you choose to add this option or not, still a very nice plugin. Great work man!

**Comment by fabianmakila** [comment]
I can add this once the configuration library I'm using supports optional values. Since I don't expect the majority to use this feature it'd be nice if it wouldn't be there by default.
